Solving errors in release.yaml file (#176)
Signed-off-by: Montse Ortega <mortegag@redhat.com>

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -78,10 +78,10 @@ jobs:
             --data-binary @apps/agent/dist/agent-latest.tgz \
             "${upload_url}?name=agent-latest.tgz")
           http_code="${response: -3}"
-+          if [ "$http_code" -ne 201 ]; then
-+            echo "Failed to upload agent-latest.tgz. HTTP status: $http_code"
-+            exit 1
-+          fi
+          if [ "$http_code" -ne 201 ]; then
+            echo "Failed to upload agent-latest.tgz. HTTP status: $http_code"
+            exit 1
+          fi
 
       - name: Configure npm credentials
         run: echo "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}" > ~/.npmrc
